name:  testing
on:
  workflow_dispatch
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5
         id: cp313
         with:
          python-version: "3.13"
       - run: pipx run --python '${{ steps.cp313.outputs.python-path }}' nox --version
            
          
             

             
