name:  testing
on:
  workflow_dispatch
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          id: cp312
          with:
           python-version: "3.9.0 - 3.12.0"
        - run: echo '${{ steps.cp312.outputs.python-version }}'
            
          
             

             
